### ISSUE TITLE
Internationalization, localization, translation

### ISSUE THREAD

**Issue by nfreear** [nfreear/gaad-widget#4]
Please help by correcting and adding translations ~ [TEMPLATE](#issuecomment-315536012).

Like any software translation, the [TEMPLATE](#issuecomment-315536012) contains a number of _placeholders_ -- places where bits of dynamic/ changeable text will be inserted. _Placeholders_ should not be translated -- instead leave them embedded in your translation in the appropriate place. The _placeholders_ are denoted by curly braces, for example, _{y}_ is for year, _{g}_ is for "_Global Accessibility Awareness Day_" (or its translation), and so on.

There is also HTML markup, for example, `<a {at}>..</a>`, which should be preserved intact.

As there only five strings to be translated at present, you can do the work in any software you feel comfortable with (Google Doc, MS Word, a comment in this GitHub issue ...)

## Translations

* Translations: [@nfreear/gaad-widget `../locales/`][json] - JSON format
* Template: [@nfreear/gaad-widget `../locales/template.json`][template]

### Before

- [x] English ~ "Join us on Thursday May 18th, 2017 and mark the 6th GAAD."
- [x] Français ~ "[Rejoignez-nous le jeudi 18 mai 2017 et marquez le 6ème GAAD.][fr-bf]"
- [ ] Chinese (simplified) ~ "[在2017年5月18日星期四加入我们，标志着NNNth GAAD。][zh-cn]"

### After

* English ~ "Put next year's GAAD, Thursday May 17th, 2018, in your diary. See you then!"
* Français ~ ["Mettez le GAAD de l'année prochaine, le jeudi 17 mai 2018 dans votre journal. À plus tard!][fr-af]
* Chinese (simplified) ~ "[把明年的GAAD，2018年5月17日星期四在你的日记。 回头见！][zh-cn]"

---
## Target?

1. English (en),
2. español / Spanish (es),
3. Français / French (fr),
4. 日本人 / Japanese (jp),
5. русский / Russian (ru),
6. português brasileiro / Portugese (Brazilian) (pt-BR).

(Based on the list of translations at the foot of, http://globalaccessibilityawarenessday.org)

Plus:

7. 简体中文 / Simplified Chinese (zh-CN)‎.

---
[TEMPLATE](#issuecomment-315536012)

[json]: https://github.com/nfreear/gaad-widget/tree/3.x/locales
[template]: https://github.com/nfreear/gaad-widget/blob/3.x/locales/template.json "JSON template"
[fr-bf]: https://translate.google.com/#auto/fr/Join%20us%20on%20Thursday%20May%2018th%2C%202017%20and%20mark%20the%206th%20GAAD.
[fr-af]: https://translate.google.com/#auto/fr/Put%20next%20year's%20GAAD%2C%20Thursday%20May%2017th%2C%202018%2C%20in%20your%20diary.%20See%20you%20then!

[zh-cn]: https://translate.google.com/#auto/zh-CN/Join%20us%20on%20Thursday%20May%2018%2C%202017%20and%20mark%20the%20NNNth%20GAAD.%0A%0APut%20next%20year's%20GAAD%2C%20Thursday%20May%2017%2C%202018%2C%20in%20your%20diary.%20See%20you%20then!
  "Chinese (simplified) - mainland China"

* https://translate.google.com/#auto/es/Put%20next%20year's%20%22World%20Day%20to%20Promote%20Awareness%20about%20Web%20Accessibility%22%2C%20Thursday%20May%2017th%2C%202019%2C%20in%20your%20diary.%20See%20you%20then!

**Comment by nfreear** [comment]
---
# Template

```yaml
- name original: "Global Accessibility Awareness Day (GAAD)"
- name translate:
- before orig: "Join us on Thursday May {d}{th}, {y} and mark the {x}th <a {at}>{g}</a>."
- before trans:
- after orig: "Put next year's <a {at}>{g}</a>, Thursday May {d}{th}, {y}, in your diary. See you then!",
- after trans:
- howto orig: "Put {z} on your site"
- howto trans:
- calendar orig: "Download an iCal calendar file"
- calendar trans:
```

---
Not needed?

```yaml
- powered orig:  "Powered by {z}"
- powered trans: 
```

---
### YAML template

```yaml
# TEMPLATE - English (en)
# Thanks for contributing! (This is just a comment or note.)

# Leave the language code '_lang_' as is, unless you know what you're doing!
_lang_:

  #__name_orig: Global Accessibility Awareness Day (GAAD)
  name: ""

  #__translators: Please leave {d}, {th} and other placeholders as they are, because they are needed by the software.
  #__before_orig: Join us on Thursday May {d}{th}, {y} and mark the {x}th <a {at}>{g}</a>.
  before: ""

  #__after_orig: Put next year's <a {at}>{g}</a>, Thursday May {d}{th}, {y}, in your diary. See you then!
  after: ""

  #__url_orig: http://globalaccessibilityawarenessday.org
  url: ""

  #__howto_orig: Put {z} on your site
  howto: ""

  #__calendar_orig: Download an iCal calendar file
  calendar: ""

# End.
```
